### ISSUE TITLE
Can't install addon

### ISSUE THREAD

**Issue by iurab** [jmplonka/InventorLoader#12]
Is there a way to debug and see what can cause the install to fail?
The needed packages are installed:

```
➜ python3 -m pip install xlutils
Requirement already satisfied: xlutils in /usr/local/lib/python3.5/dist-packages (2.0.0)
Requirement already satisfied: xlrd>=0.7.2 in /usr/local/lib/python3.5/dist-packages (from xlutils) (1.1.0)
Requirement already satisfied: xlwt>=0.7.4 in /usr/local/lib/python3.5/dist-packages (from xlutils) (1.3.0)
~
➜ python3 -m pip install olefile
Requirement already satisfied: olefile in /usr/local/lib/python3.5/dist-packages (0.45.1)

➜ python2 -m pip install xlutils
Requirement already satisfied: xlutils in /usr/local/lib/python2.7/dist-packages (2.0.0)
Requirement already satisfied: xlwt>=0.7.4 in /usr/local/lib/python2.7/dist-packages (from xlutils) (1.3.0)
Requirement already satisfied: xlrd>=0.7.2 in /usr/local/lib/python2.7/dist-packages (from xlutils) (1.1.0)
~
➜ python2 -m pip install olefile
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (0.45.1)
```

**Comment by jmplonka** [comment]
To be honest, I never used pip to install one of these packages.

I downloaded and extracted the available archives (ref. to libs.zip) and run the setup.py in each of the subfolders (e.g.):
`.\InventorLoader\libs\olefile>` python.exe setup.py install

But be careful with the path environment as FC is using its own python!

**Comment by wisniewski94** [comment]
Is there some guide for non-python developers, how to install, run and use this tool? Such mini guide would be very usefull. Thanks and keep it up!

**Comment by jmplonka** [comment]
I updated the readme for the repo. 
@wisniewski94 : thank you for your feedback. Is it now better understandable?

**Comment by jmplonka** [comment]
can I close the issue now?

**Comment by luzpaz** [comment]
Just a reference: https://github.com/FreeCAD/FreeCAD-addons/issues/71

**Comment by luzpaz** [comment]
Not sure if we should close this yet.

**Comment by luzpaz** [comment]
@iurab still an issue?
Please follow https://forum.freecadweb.org/viewtopic.php?f=22&t=29584

**Comment by iurab** [comment]
No, the issue can be closed :)

**Comment by luzpaz** [comment]
@jmplonka please close issue

**Comment by jkbgbr** [comment]
I just tried to install the addon through the Addon Manager of 0.18.4 under win10 - did not succeed for the first try as the xls- and ole-related modules were missing. The addon manager just tells to install the missing modules, but no further instructions are given. I wonder if this happens if the freecad install path requires elevated prompt.
So I went to the freecad install directory, found the pip.exe and using this I could install the missing modules. This is IMHO not straightfoward for people less educated in the inner workings of python.

Perhaps more importantly: is this an InventorLoader issue?

**Comment by jmplonka** [comment]
I tried several ways to automatise the installation of the missing packages. Until yet I didn't find a suitable and robust way.
Unfortunately I know only litte about the FC's Addon-Manager. Maybe someone is able and willing to support me on this issue.

**Comment by luzpaz** [comment]
@jmplonka feel free to discuss this on https://forum.freecadweb.org/viewtopic.php?f=22&t=29584
